---
title: "Penalized Domains"
output: html_document
date: "2022-11-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyr)
library(httr)
library(DBI)
library(urltools)
library(ggplot2)
library(zoo)

conn <- dbConnect(RSQLite::SQLite(), "../data/hacker-news.sqlite")

# story_urls <- 
#   readr::read_delim(
#     "../data/hacker-news-urls.csv",
#     col_names = c("idx", "id", "url"),
#     delim = ",",
#     skip = 1) %>%
#   select(-idx) %>% 
#   mutate(domain = domain(url)) %>% 
#   mutate(id = as.integer(id))



```



```{r}
dbWriteTable(conn, "storyDomains", story_urls, overwrite = TRUE)
```


```{r}
tbc(conn, "storyDomains") %>% 
  select
```



```{r}
second_chance_pool_ids <- 
  tbl(conn, "dataset") %>% 
  filter(!is.null(topRank)) %>% 
  mutate(
    ageHours = (sampleTime - submissionTime) / 60 / 60,
    hnScore = ((score - 1)^0.8) / ((ageHours + 2)^1.8)
  ) %>% 
  select(tick, id, score, ageHours, hnScore, topRank) %>% 
  mutate(ageHoursSq = ageHours * ageHours) %>% 
  left_join(
    tbl(conn, "dataset") %>% 
      filter(topRank >= 61) %>% 
      mutate(
        ageHours = (sampleTime - submissionTime) / 60 / 60,
        hnScore = ((score - 1)^0.8) / ((ageHours + 2)^1.8)
      ) %>% 
      group_by(tick) %>% 
      summarize(lowestScoreOnPage3 = min(hnScore)) %>% 
      ungroup(),
    by = "tick"
  ) %>% 
  filter(hnScore < lowestScoreOnPage3) %>% 
  select(id) %>% 
  distinct() %>% 
  show_query()

second_chance_pool_ids

dbExecute(conn, "
create table secondChancePool 
as (
SELECT DISTINCT `id`
FROM (
  SELECT
    `LHS`.`tick` AS `tick`,
    `id`,
    `score`,
    `ageHours`,
    `hnScore`,
    `topRank`,
    `ageHoursSq`,
    `lowestScoreOnPage3`
  FROM (
    SELECT *, `ageHours` * `ageHours` AS `ageHoursSq`
    FROM (
      SELECT
        `tick`,
        `id`,
        `score`,
        `ageHours`,
        (POWER((`score` - 1.0), 0.8)) / (POWER((`ageHours` + 2.0), 1.8)) AS `hnScore`,
        `topRank`
      FROM (
        SELECT
          *,
          ((`sampleTime` - `submissionTime`) / 60.0) / 60.0 AS `ageHours`
        FROM `dataset`
        WHERE (NOT((`topRank` IS NULL)))
      )
    )
  ) AS `LHS`
  LEFT JOIN (
    SELECT `tick`, MIN(`hnScore`) AS `lowestScoreOnPage3`
    FROM (
      SELECT
        *,
        (POWER((`score` - 1.0), 0.8)) / (POWER((`ageHours` + 2.0), 1.8)) AS `hnScore`
      FROM (
        SELECT
          *,
          ((`sampleTime` - `submissionTime`) / 60.0) / 60.0 AS `ageHours`
        FROM `dataset`
        WHERE (`topRank` >= 61.0)
      )
    )
    GROUP BY `tick`
  ) AS `RHS`
    ON (`LHS`.`tick` = `RHS`.`tick`)
)
WHERE (`hnScore` < `lowestScoreOnPage3`)
)
")

```


```{r}
start_tick <- 1
step_size <- 100000

rank_penalty_ratios <- 
    tbl(conn, "dataset") %>% 
    filter(
      !is.na(topRank)
    ) %>% 
    left_join(tbl(conn, "storyDomains") %>% select(id, domain), by = "id") %>% 
    mutate(
      ageHours = (sampleTime - submissionTime) / 60 / 60,
      hnScore = ((score - 1)^0.8) / ((ageHours + 2)^1.8)
    ) %>% 
    anti_join(tbl(conn, "secondChancePool"), by = "id") %>% 
    arrange(sampleTime, topRank) %>% 
    mutate(cleanedTopRank = row_number()) %>% 
    ungroup() %>% 
    arrange(sampleTime, desc(hnScore)) %>% 
    group_by(sampleTime) %>% 
    mutate(expectedTopRank = row_number()) %>% 
    ungroup() %>% 
    mutate(
      rankPenalty = expectedTopRank - cleanedTopRank,
      hasRankPenalty = rankPenalty < 0
    ) %>% 
    select(id, domain, hasRankPenalty) %>% 
    distinct() %>% 
    group_by(domain, hasRankPenalty) %>% 
    summarize(count = n()) %>% 
    ungroup() %>% 
    data.frame() %>% 
    pivot_wider(
      id_cols = c("domain"),
      names_from = "hasRankPenalty",
      names_prefix = "hasRankPenalty",
      values_from = "count"
    ) %>%
    replace_na(list("hasRankPenalty1" = 0, "hasRankPenalty0" = 0)) %>% 
    mutate(
      domainOccurrences = hasRankPenalty1 + hasRankPenalty0,
      hasRankPenaltyPercentage = hasRankPenalty1 / domainOccurrences
    ) %>% 
    arrange(desc(hasRankPenaltyPercentage)) %>% 
    tibble()
  
  # rank_penalty_ratios <- 
  #   rank_penalty_ratios %>% 
  #   bind_rows(samp) %>% 
  #   group_by(domain) %>% 
  #   summarize(
  #     hasRankPenaltyFALSE = sum(hasRankPenaltyFALSE),
  #     hasRankPenaltyTRUE = sum(hasRankPenaltyTRUE)
  #   ) %>% 
  #   ungroup()
  # 
# }

# rank_penalty_ratios <- 
#   rank_penalty_ratios %>%
#   replace_na(list("hasRankPenaltyTRUE" = 0, "hasRankPenaltyFALSE" = 0)) %>% 
#   mutate(
#     domainOccurrences = hasRankPenaltyTRUE + hasRankPenaltyFALSE,
#     hasRankPenaltyPercentage = hasRankPenaltyTRUE / domainOccurrences
#   ) %>% 
#   arrange(desc(hasRankPenaltyPercentage)) %>% 
#   tibble()

```

```{r}
dbWriteTable(conn, "domainPenalties", rank_penalty_ratios)
```


```{r}
rank_penalty_ratios %>% 
  arrange(desc(hasRankPenaltyPercentage), desc(domainOccurrences))
```


The following query implements a heuristic to find the most likely candidates for domain penalties:

```{sql}
with hnScores as (
    select 
        *
        , cast(sampleTime - submissionTime as real)/3600 as ageHours
        , pow(score-1, 0.8) / pow(cast(sampleTime - submissionTime as real)/3600+2, 1.8) as hnScore, secondChancePool.id is not null as scp
    from dataset
    left outer join secondChancePool using(id)
    left outer join storyDomains using(id)
),
penalties as (
    select 
        id
        , topRank
        , score as votes
        , hnScore
        , domain
        , 1 - min(hnScore) filter (where scp = 0 and ageHours < 24 and topRank is not null) over (partition by sampleTime order by topRank rows unbounded preceding) / hnScore as penalty
    from hnScores
    where topRank is not null
    and topRank > 1
    and domain is not null
    limit 1000000
)
select 
    domain
    , count(*) as c
    , avg(penalty) avgPenalty
    , min(penalty) minPenalty
    , max(penalty) maxPenalty
from penalties
where penalty >= 0
group by domain
order by avgPenalty desc
```



```{r}
penalty_candidates <- 
  rank_penalty_ratios %>% 
  filter(domainOccurrences >= 10, hasRankPenaltyPercentage == 1) %>% 
  arrange(desc(domainOccurrences))
```


```{r}
penalized_domains <- 
  rank_penalty_ratios %>% 
  filter(domainOccurrences >= 10, hasRankPenaltyPercentage == 1) %>% 
  arrange(desc(domainOccurrences)) %>% 
  select(domain) %>% 
  mutate(isPenalizedDomain = TRUE)


story_urls %>% 
  mutate(domain = domain(url)) %>% 
  left_join(penalized_domains, by = "domain") %>% 
  replace_na(list("isPenalizedDomain" = FALSE)) %>% 
  select(id, domain, isPenalizedDomain) %>% 
  group_by(isPenalizedDomain) %>% 
  summarize(count = n()) %>% 
  ungroup() %>% 
  pivot_wider(
    names_from = "isPenalizedDomain",
    names_prefix = "isPenalizedDomain",
    values_from = "count"
  ) %>% 
  mutate(
    overallStoryCount = isPenalizedDomainFALSE + isPenalizedDomainTRUE,
    penalizedDomainsPercentage = isPenalizedDomainTRUE / overallStoryCount
  ) %>% 
  select(penalizedDomainsPercentage)
  
```


```{r}
domain_penalized_story_candidates <- 
  story_urls %>% 
  mutate(domain = domain(url)) %>% 
  select(id, domain) %>% 
  inner_join(penalized_domains %>% select(domain), by = "domain")


domain_penalized_story_candidates %>% 
  group_by(domain) %>% 
  summarize(count = n()) %>% 
  ungroup() %>% 
  arrange(desc(count))
```

```{r}
max_tick <-
  dbGetQuery(conn, "
    SELECT max(tick) as maxTick
    FROM dataset
  ") %>%
  pull(maxTick) %>%
  max()

step_size <- 10000

guardian_stories <- 
  domain_penalized_story_candidates %>%
  # filter(domain == "www.theguardian.com") %>% 
  filter(domain == "arstechnica.com") %>% 
  select(id)

proportionality_estimation <- data.frame()

for (start_tick in seq(1, max_tick, step_size)) {
  
  start_tick <- 1
  
  samp <- 
    tbl(conn, "dataset") %>% 
    filter(
      tick >= start_tick,
      tick < start_tick + step_size
    ) %>% 
    filter(!is.na(topRank)) %>% 
    mutate(ageHours = (sampleTime - submissionTime) / 60 / 60) %>% 
    mutate(hnScore = ((score - 1)^0.8) / ((ageHours + 2)^1.8)) %>% 
    arrange(tick, topRank) %>% 
    group_by(tick) %>% 
    mutate(
      firstHigherRankHNScore = lag(hnScore),
      firstLowerRankHNScore = lead(hnScore)
    ) %>% 
    ungroup() %>% 
    select(
      tick, id, topRank, hnScore, firstHigherRankHNScore, firstLowerRankHNScore
    ) %>% 
    data.frame() %>%  # perhaps move up if viable to avoid weird sql translation errors
    inner_join(guardian_stories, by = "id")
  
  proportionality_estimation <- 
    proportionality_estimation %>% bind_rows(samp)
}

```

```{r}
proportionality_estimation %>% 
  filter(firstHigherRankHNScore > firstLowerRankHNScore) %>%
  mutate(
    lower = firstLowerRankHNScore / hnScore,
    upper = firstHigherRankHNScore / hnScore
  ) %>% 
  pivot_longer(
    cols = c("lower", "upper"),
    names_to = "estimateType",
    values_to = "estimate"
  ) %>% 
  ggplot(aes(x = estimate, y = as.factor(id), color = estimateType)) +
  geom_point(alpha = 0.05)


proportionality_estimation %>% 
  select(id) %>% 
  distinct()
```




```{r}
# sample_stories <- sample(fullstories_ids, 1000)

samp <-
  tbl(conn, "dataset") %>% 
  inner_join(tbl(conn, "fullstories"), by = "id") %>% 
  filter(
    # id %in% sample_stories,
    !is.na(topRank),
    sampleTime >= 1637705407 + 604800,
    sampleTime <= 1637705407 + 4838400
  ) %>% 
  data.frame() %>% 
  left_join(story_urls, by = "id") %>% 
  filter(!is.null(url)) %>%
  mutate(ageHours = (sampleTime - submissionTime) / 60 / 60) %>% 
  mutate(hnScore = ((score - 1)^0.8) / ((ageHours + 2)^1.8)) %>% 
  mutate(domain = domain(url)) %>% 
  arrange(sampleTime, desc(hnScore)) %>% 
  group_by(sampleTime) %>% 
  mutate(expectedTopRank = row_number()) %>% 
  ungroup() %>% 
  mutate(
    rankPenalty = expectedTopRank - topRank,
    hasRankPenalty = rankPenalty < 0
  )


rank_penalty_ratios <- 
  samp %>% 
  arrange(sampleTime, desc(hnScore)) %>% 
  select(id, domain, hasRankPenalty) %>% 
  distinct() %>% 
  group_by(domain, hasRankPenalty) %>% 
  summarize(count = n()) %>% 
  ungroup() %>% 
  pivot_wider(
    id_cols = c("domain"),
    names_from = "hasRankPenalty",
    names_prefix = "hasRankPenalty",
    values_from = "count"
  ) %>% 
  replace_na(list("hasRankPenaltyTRUE" = 0, "hasRankPenaltyFALSE" = 0)) %>% 
  mutate(
    domainOccurrences = hasRankPenaltyTRUE + hasRankPenaltyFALSE,
    hasRankPenaltyPercentage = hasRankPenaltyTRUE / domainOccurrences
  ) %>% 
  filter(domainOccurrences >= 10) %>% 
  arrange(desc(hasRankPenaltyPercentage)) %>% 
  tibble()


# check for number of comments  
samp %>% 
  mutate(over40Comments = descendants >= 40) %>% 
  select(id, over40Comments, hasRankPenalty) %>% 
  distinct() %>% 
  group_by(over40Comments, hasRankPenalty) %>% 
  summarize(count = n()) %>%
  ungroup() %>% 
  pivot_wider(
    id_cols = c("over40Comments"),
    names_from = "hasRankPenalty",
    names_prefix = "hasRankPenalty",
    values_from = "count"
  ) %>% 
  mutate(
    hasRankPenaltyPercentage =
      hasRankPenaltyTRUE / (hasRankPenaltyTRUE + hasRankPenaltyFALSE)
  )


```

```{r}
domain_distribution <- 
  story_urls %>% 
  mutate(domain = domain(url)) %>% 
  group_by(domain) %>% 
  summarize(count = n()) %>% 
  ungroup() %>% 
  arrange(desc(count)) %>% 
  tibble()

domain_distribution %>% 
  ggplot(aes(x = count)) +
  geom_histogram(binwidth = 1) +
  scale_x_continuous(limits = c(0, 100))
```


```{r}
tbl(conn, "domainPenalties2") %>% 
  group_by(id) %>% 
  summarize(
    domain = max(domain),
    minPenalty = min(penalty),
    maxPenalty = max(penalty),
    avgPenalty = mean(penalty),
    sampleCount = n()
  ) %>%
  ungroup() -> summaryPenaltiesSql 


summaryPenaltiesSql %>% 
  group_by(domain) %>%
  summarize(nSampleCount = n()) %>%
  ungroup() %>%
  arrange(desc(nSampleCount)) %>% 
  head(20) -> top20Sql

summaryPenaltiesSql %>% 
  inner_join(top20Sql %>% select(domain), by = "domain") %>% 
  filter(minPenalty > 0) %>% 
  # pivot_longer(
  #   cols = c("minPenalty", "avgPenalty", "maxPenalty"),
  #   names_to = "metric",
  #   values_to = "value"
  # ) %>% 
  ggplot(aes(x = avgPenalty)) + 
    geom_histogram() +
    facet_wrap(. ~ domain, nrow = 20, scales = "free_y")

ggsave("avgPenalties.png", height = 20, width = 5)
```


```{r}
summaryPenaltiesSql %>% 
  mutate(penaltyDiff = round(maxPenalty - avgPenalty, 3)) %>% 
  data.frame() %>% 
  sample_n(10)
  # arrange(desc(sampleCount)) %>% 
  arrange(desc(penaltyDiff)) %>% 
  identity()
```


```{r}
tbl(conn, "domainPenalties2") %>% 
  filter(descendants > 100) %>% 
  group_by(id) %>% 
  summarize(
    maxDescendants = max(descendants),
    nSamples = n()
  ) %>% 
  ungroup()
```


```{r}
tbl(conn, "domainPenalties2") %>% 
  group_by(id) %>% 
  mutate(
    avgPenalty = mean(penalty),
    
  )
  filter(descendants > 400) %>% 
```


```{r}
sample_id <- 29905630
sample_id <- 29348978
sample_id <- 29680861
sample_id <- 29324551  # many comments, many samples
sample_id <- 30087783

tbl(conn, "domainPenalties2") %>% 
  filter(id == sample_id) %>% 
  filter(!is.na(penalty)) %>%
  mutate(relTime = (sampleTime - min(sampleTime)) / 3600) %>% 
  data.frame() %>% 
  arrange(sampleTime) %>% 
  mutate(rollingMean = rollmean(penalty, k = 100, fill = NA)) %>% 
  pivot_longer(
    cols = c("penalty", "rollingMean"), 
    names_to = "name",
    values_to = "value"
  ) %>% 
  ggplot(aes(x = relTime, y = value, color = name)) +
   geom_point()


tbl(conn, "domainPenalties2") %>% 
  filter(id == sample_id) %>% 
  mutate(relTime = (sampleTime - min(sampleTime)) / 3600) %>% 
  ggplot(aes(x = relTime, y = topRank)) +
    geom_point() +
    scale_y_continuous(trans = "reverse")


tbl(conn, "domainPenalties2") %>% 
  filter(id == sample_id) %>% 
  mutate(relTime = (sampleTime - min(sampleTime)) / 3600) %>% 
  ggplot(aes(x = relTime, y = descendants)) +
    geom_point()
```


```{sql}
drop table if exists domainPenalties2;

create table domainPenalties2
as
with hnScores as (
    select 
        *
        , cast(sampleTime - submissionTime as real)/3600 as ageHours
        , pow(score-1, 0.8) / pow(cast(sampleTime - submissionTime as real)/3600+2, 1.8) as hnScore, secondChancePool.id is not null as scp
    from dataset
    left outer join secondChancePool using(id)
    left outer join storyDomains using(id)
    join fullstories using(id)
),
penalties as (
    select 
        id
        , topRank
        , score as votes
        , hnScore
        , domain
        , sampleTime
        , descendants
        , 1 - min(hnScore) filter (where scp = 0 and ageHours < 24 and topRank is not null) over (partition by sampleTime order by topRank rows unbounded preceding) / hnScore as penalty
    from hnScores
    where topRank is not null
    and topRank > 1
    and domain is not null
)
select 
    *
from penalties;

create index domain_penalties_2_id_index on `domainPenalties2`(id, domain, penalty);
```



```{r}
dbDisconnect(conn)
```

