---
title: "bauidetrn"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(magrittr)
library(dplyr)
```

## R Markdown

```{r}
d <- read.table(file.path("..", "data.tsv"))


s <- 0.65 
# s <- 0.36
# s <- 0.18
t <- 3.7
scaling_func <- function(x) {
  # 1 / (1 + x * floor(x / 30))
  # 1 / (x ^ s * floor((x + 1) / 30 + 1))
  
  page_shift <- floor(x / 30) * 30
  page_scale <- floor(x / 30 + 1)
  
  # 1 / ((x - page_shift + 1) ^ (s / (1.8 ^ (page_scale - 1))) * page_scale ^ t)
  1 / (1 + x * floor(x / 30 + 1))
}

g <- d %>%  
  ggplot(aes(x = V1, y = V2 / scaling_func(V1))) + 
  geom_bar(stat = "identity", width = 1) +
  coord_flip() +
  scale_x_continuous(trans = "reverse") +
  geom_vline(xintercept = 29.5, linetype = "dashed") +
  geom_vline(xintercept = 59.5, linetype = "dashed") +
  annotate("text", x = 33, y = 0.05, label = "page 2") +
  annotate("text", x = 63, y = 0.05, label = "page 3") +
  labs(y = "Votes / Impression Ratio",
       x = "Front Page Rank") +
  theme_bw()
g
ggsave(filename = "vote-impression-ratio.png", device = "png")
```

```{r}
d
```

```{r}

g <- d %>%  
  ggplot(aes(x = V1, y = V2 / scaling_func(V1))) + 
  geom_bar(stat = "identity", width = 1) +
  coord_flip() +
  scale_x_continuous(trans = "reverse") +
  geom_vline(xintercept = 29.5, linetype = "dashed") +
  geom_vline(xintercept = 59.5, linetype = "dashed") +
  annotate("text", x = 33, y = 0.05, label = "page 2") +
  annotate("text", x = 63, y = 0.05, label = "page 3") +
  labs(y = "Fraction of Votes",
       x = "Front Page Rank") +
  theme_bw()
g
# ggsave(filename = "votehist.svg", device = "svg")
```

```

