---
title: "Fitting Metrics"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(DBI)
library(dplyr)
library(ggplot2)
```


## Connect to Database

```{r}
con <- RSQLite::dbConnect(RSQLite::SQLite(), file.path("..", "hacker-news-dataset.sqlite"))
```


# Work with Database

Load a table:

```{r}
tbl(con, "dataset") %>% 
  head(20)
```


```{r}

fitting_table <- dbGetQuery(
  con, 
  "select id, sampleTime, tick, sum(score) as sum_score, sum(gain) as sum_gain from dataset where toprank is not null and samplingWindow = 3 group by tick"
) %>% 
  inner_join(tbl(con, "fullstories") %>% data.frame(), by = "id") 

fitting_table %>%
  filter(sum_gain < 1000) %>% 
  ggplot(aes(x = lubridate::as_datetime(sampleTime), y = sum_gain)) +
  # geom_line() +
  geom_point(size = 0.4) +
  scale_y_log10()

```

```{r}

dbGetQuery(
  con, 
  "
  select * from dataset 
  where topRank is not null and newRank is null
  "
)

```




# Disconnect from Database

Don't forget to disconnect after session:

```{r}
RSQLite::dbDisconnect(conn = con)
```


