---
title: "Improving the Hacker News Algorithm (Part 2)"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(DBI)
library(dplyr)
library(ggplot2)
library(lubridate)
```


## Connect to Database

```{r}
con <- RSQLite::dbConnect(RSQLite::SQLite(), "../hacker-news-dataset.sqlite")
```



# Vote Gain on Top (and/or New) Page by Rank for a Given Window of One Hour

```{r}

tbl(con, "dataset") %>% 
  filter(!(tick == 0)) %>% 
  filter((sampleTime >= 1616415331) & (sampleTime <= 1616415331 + 3600)) %>% 
  select(topRank, newRank, gain) %>% 
  ggplot(aes(x = topRank, y = gain)) + 
  geom_histogram(stat = "identity")
  
```


# Working with Times and Week Days

1 min = 60 sec
1 hour = 3,600 sec
1 day = 86,400 sec
1 week = 604,800 sec

```{r}

tbl(con, "dataset") %>%
  select(sampleTime, tick, topRank, newRank, gain) %>% 
  as.data.frame() %>% 
  filter(!(tick == 0)) %>% 
  mutate(tickBinnedHour = tick %/% 60) %>% 
  group_by(tickBinnedHour) %>% 
  summarise(sumGain = sum(gain)) %>% 
  ungroup() %>% 
  filter((tickBinnedHour >= 100) & (tickBinnedHour <= 200)) %>% 
  ggplot(aes(x = tickBinnedHour, y = sumGain)) +
  geom_point() +
  geom_line() +
  scale_x_continuous(breaks = seq(96, 192, by = 24))
  
```

```{r}

tbl(con, "dataset") %>% 
  select(sampleTime) %>% 
  ggplot(aes(x = as_datetime(sampleTime))) +
  geom_histogram()

```




```{r}
# Language settings to english
Sys.setlocale("LC_ALL","en_US.UTF-8")

# Define a period of a week to show periodicity of votes
april_5 <- as.numeric(lubridate::ymd_hms("2021-04-05T00:00:00"))
april_13 <- as.numeric(lubridate::ymd_hms("2021-04-13T00:00:00"))

# Define another period to see if it replicates
may_3 <- as.numeric(lubridate::ymd_hms("2021-05-03T00:00:00"))
may_11 <- as.numeric(lubridate::ymd_hms("2021-05-11T00:00:00"))
```


```{r}
begin_may <- tbl(con, "dataset") %>% 
  select(sampleTime, topRank, newRank, gain) %>% 
  filter(sampleTime >= may_3) %>% 
  filter(sampleTime < may_11) %>% 
  as_tibble() %>% 
  mutate(dayOfWeek = wday(as_datetime(sampleTime), label = TRUE, week_start = 1),
         hourOfDay = hour(as_datetime(sampleTime)))
```


```{r}
begin_may %>% 
  group_by(dayOfWeek, hourOfDay) %>% 
  summarise(gainHour = sum(gain, na.rm = TRUE)) %>% 
  ungroup() %>% 
  arrange(dayOfWeek) %>% 
  ggplot(aes(x = hourOfDay, y = gainHour, color = dayOfWeek)) +
  geom_point() +
  geom_line()
```


```{r}
begin_may %>% 
  group_by(dayOfWeek) %>% 
  summarise(gainDay = sum(gain, na.rm = TRUE)) %>% 
  ungroup() %>% 
  ggplot(aes(x = as.numeric(dayOfWeek), y = gainDay)) +
  geom_bar(stat = "identity", fill = "#ff6600", alpha = 0.5) +
  geom_line() +
  geom_point(shape = 21, fill = "white", size = 5) +
  labs(x = "Week Day",
       y = "Submitted Votes") +
  scale_x_continuous(breaks = seq(1, 7, 1)) +
  theme(text = element_text(family = "courier"),
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = "#f6f6ef"),
        axis.line = element_line(color = "black"))
```

```{r}

data_cropped <- tbl(con, "dataset") %>% 
  select(sampleTime, samplingWindow, topRank, newRank, gain) %>% 
  as_tibble() %>% 
  mutate(date = date(as_datetime(sampleTime))) %>% 
  group_by(samplingWindow) %>% 
  mutate(min_date = min(date), max_date = max(date)) %>% 
  ungroup() %>% 
  filter(!(date == min_date) & !(date == max_date)) %>% 
  mutate(dayOfWeek = wday(as_datetime(sampleTime), label = TRUE, week_start = 1),
         hourOfDay = hour(as_datetime(sampleTime)))

data_cropped %>% 
  group_by(dayOfWeek, date) %>% 
  summarize(sumGain = sum(gain, na.rm = TRUE)) %>% 
  ungroup() %>% 
  mutate(week = week(date)) %>% 
  ggplot(aes(x = as.numeric(dayOfWeek), y = sumGain, color = week, group = week)) +
  geom_point(alpha = 0.5, size = 3) +
  geom_line()


```


# Disconnect from Database

Don't forget to disconnect after session:

```{r}
RSQLite::dbDisconnect(conn = con)
```

