---
title: "Day of Week and Time of Day"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(DBI)
library(dplyr)
library(ggplot2)
con <- RSQLite::dbConnect(RSQLite::SQLite(), "../hacker-news-dataset.sqlite")
```



```{r}
Sys.setlocale("LC_ALL","en_US.UTF-8")

dbGetQuery(con, "
  SELECT sampleTime, topRank, gain
  FROM dataset
") %>% 
  as_tibble() %>%
  mutate(sampleTimeDateTime = lubridate::as_datetime(sampleTime)) %>% 
  mutate(sampleTimeDate = lubridate::date(sampleTimeDateTime),
         sampleTimeWeekday = lubridate::wday(sampleTimeDateTime, label = TRUE, week_start = 1),
         sampleTimeHour = lubridate::hour(sampleTimeDateTime),
         sampleTimeMinute = lubridate::minute(sampleTimeDateTime)) %>%  
  group_by(sampleTimeDate, sampleTimeWeekday, sampleTimeHour, sampleTimeMinute) %>% 
  summarize(sumGainInMinute = sum(gain)) %>% 
  ungroup() -> data_1

data_1 %>% 
  group_by(sampleTimeDate, sampleTimeWeekday, sampleTimeHour) %>% 
  summarize(meanPerMinuteGainInHour = mean(sumGainInMinute)) %>% 
  ungroup() -> data_2

```


```{r}
dbGetQuery(con, "
  SELECT sampleTime, topRank, gain, samplingWindow
  FROM dataset
") %>% 
  as_tibble() %>%
  mutate(sampleTimeDateTime = lubridate::as_datetime(sampleTime)) %>% 
  mutate(sampleTimeDatetimeRounded = lubridate::floor_date(sampleTimeDateTime, unit = "hour")) %>% 
  group_by(sampleTimeDatetimeRounded) %>% 
  summarize(sumGainInHour = sum(gain),
            countSamples = n(),
            meanGainInHour = mean(gain)) %>% 
  ungroup() -> d

d %>% 
  ggplot(aes(x = sampleTimeDatetimeRounded, y = meanGainInHour, color = countSamples)) +
  geom_point() +
  scale_color_viridis_c()

ggsave("timeline.png", width = 40, height = 5)
```



```{r}

data_2 %>% 
  filter(meanPerMinuteGainInHour < 40, meanPerMinuteGainInHour > 0) %>%
  mutate(meanPerHourGainInHour = meanPerMinuteGainInHour * 60) %>% 
  ggplot(aes(x = sampleTimeHour, y = meanPerHourGainInHour)) +
  geom_smooth(se = FALSE, size = 1, color = "grey") +
  geom_point(alpha = 0.6, aes(color = factor(sampleTimeWeekday))) +
  scale_x_continuous(breaks = c(0, 6, 12, 18)) +
  # scale_y_continuous(breaks = seq(0, 3000, by = 200)) +
  labs(x = "Time of Day",
       y = "Average Upvotes per Hour",
       caption = "collected between 2021-03-22 and 2021-05-11") +
  facet_grid(cols = vars(sampleTimeWeekday)) +
  theme(legend.position = "None",
        text = element_text(family = "Courier"),
        axis.title.x = element_text(margin = margin(t = 10, b = 10)), 
        panel.background = element_rect(fill = "#f6f6ef"),
        panel.grid.major = element_line(color = "grey90"),
        panel.grid.minor = element_blank(),
        axis.line = element_line(color = "black"))
 
ggsave("dow-tod-trend.svg", width = 8, height = 5)
ggsave("dow-tod-trend.png", width = 8, height = 5)
```



```{r}
dbGetQuery(con, "
  select *
  from dataset
  where samplingWindow == 3
  
")
```


# Disconnect from Database

Don't forget to disconnect after session:

```{r}
RSQLite::dbDisconnect(conn = con)
```

