---
title: "Quality"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(DBI)
library(dplyr)
library(ggplot2)
```


## Connect to Database

```{r}
con <- RSQLite::dbConnect(RSQLite::SQLite(), file.path("..", "hacker-news-dataset.sqlite"))
```


```{r}
RSQLite::dbDisconnect(conn = con)
```


# Work with Database



```{r}

tbl(con, "quality") %>% 
  select(localQuality4) %>% 
  filter(!(is.na(localQuality4))) %>% 
  ggplot(aes(x = localQuality4)) +
  geom_histogram(bins = 100) +
  # scale_x_continuous(limits = c(-0.05, 1.05)) +
  scale_y_log10()
  
# look into 

```


```{r}

tbl(con, "quality") %>% 
  select(localQuality4, score) %>% 
  filter(!(is.na(localQuality4))) %>% 
  ggplot(aes(x = localQuality4, y = score)) +
  geom_point(alpha = 0.2) +
  # scale_y_continuous(trans = "reverse") +
  scale_y_log10() +
  scale_x_log10() +
  NULL

```


```{r}

tbl(con, "quality") %>% 
  select(qualityQuotient, score) %>% 
  filter(!(is.na(qualityQuotient))) %>% 
  ggplot(aes(x = qualityQuotient)) +
  geom_histogram(bins = 50) +
  scale_y_log10()

```


```{r}

dbGetQuery(
  con, 
  "select newRank, sum(gain) sumGain from dataset where newRank is not null and topRank is null group by newRank;"
) %>%
  ggplot(aes(x = newRank, y = sumGain)) +
  geom_point()

```


```{r}



```



Load a table:

```{r}
tbl(con, "dataset") %>% 
  head(20)
```

Make a plot:

```{r}
tbl(con, "dataset") %>% 
  select(score) %>% 
  ggplot(aes(x = score)) +
  geom_histogram()
```


# Disconnect from Database

Don't forget to disconnect after session:

```{r}
RSQLite::dbDisconnect(conn = con)
```

